### PR TITLE
Fixed issue with /format-code formatting bot messages

### LINKED ISSUE #215: Make /format-code skip bot messages
Currently, /format-code always formats the LAST message, even if it's sent by the bot itself. This is unnecessary and not what people expect

### PR DESCRIPTION
**Pull request by sahilasopa**
closes #215

### CODE REVIEW

File: src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java [hunk 1]
```diff
@@ -28,6 +28,9 @@ public ReplyCallbackAction handleSlashCommandInteraction(SlashCommandInteraction
 		if (idOption == null) {
 			if (event.getChannel().hasLatestMessage()) {
 				id = event.getChannel().getLatestMessageIdLong();
+				if (event.getChannel().retrieveMessageById(id).complete().getAuthor().isBot()){
+					return Responses.error(event, "Missing required arguments.");
+				}
```
Comment (DynxstyGIT) [inline src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java:33]: Don't use `.complete()` calls, as they're blocking the current thread. In addition, I think it would be useful if it takes the last message that isn't sent from a bot instead of throwing an error.

**Review by DynxstyGIT — CHANGES_REQUESTED** [review]

**Review by MoonTM-GIT — CHANGES_REQUESTED** [review]
Yeah, this does not add the functionality that was described in #215.

File: src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java (hunk 1 above)
Comment (sahilasopa) [reply src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java:33]: fetch last 5 messages and format latest non bot message?

Comment (MoonTM-GIT) [reply src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java:33]: for example, yes

**Review by MoonTM-GIT — APPROVED** [review]

File: src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java [hunk 2]
```diff
@@ -19,25 +19,38 @@
...
 	public ReplyCallbackAction handleSlashCommandInteraction(SlashCommandInteractionEvent event) {
 		var idOption = event.getOption("message-id");
 		var formatOption = event.getOption("format");
+		var slashConfig = Bot.config.get(event.getGuild()).getSlashCommand();
 		String format = formatOption == null ? "java" : formatOption.getAsString();
-		long id;
 		if (idOption == null) {
 			if (event.getChannel().hasLatestMessage()) {
-				id = event.getChannel().getLatestMessageIdLong();
+				event.getChannel().getHistory().retrievePast(100) // max limit
```
Comment (danthe1st) [inline src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java:32]: I think fetching 100 messages is a little bit of an overkill.

File: src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java [hunk 3]
```diff
@@ -19,25 +19,38 @@
...
+						.map(messages -> messages)
+						.queue(messages -> {
+							for (Message message : messages) {
+								if (!message.getAuthor().isBot()){
+									id = message.getIdLong();
+									break;
+								}
+							}
+							event.getTextChannel().retrieveMessageById(id).queue(
```
Comment (danthe1st) [inline src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java:41]: `id` may be `null` if all the messages were sent by the bot (could happen in channels like the suggestion channel or looking-for-programmer if #216 is implemented and deployed)

File: src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java [hunk 4]
```diff
@@ -19,25 +19,38 @@
...
 		var idOption = event.getOption("message-id");
 		var formatOption = event.getOption("format");
+		var slashConfig = Bot.config.get(event.getGuild()).getSlashCommand();
 		String format = formatOption == null ? "java" : formatOption.getAsString();
-		long id;
 		if (idOption == null) {
 			if (event.getChannel().hasLatestMessage()) {
-				id = event.getChannel().getLatestMessageIdLong();
+				event.getChannel().getHistory().retrievePast(100) // max limit
+						.map(messages -> messages)
```
Comment (danthe1st) [inline src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java:33]: Does this have any purpose?

File: src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java (hunk 2 above)
Comment (sahilasopa) [reply src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java:32]: how many do you think we should fetch? 10?

Comment (sahilasopa) [reply src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java:32]: how many do you think we should fetch? 10?

File: src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java (hunk 3 above)
Comment (sahilasopa) [reply src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java:41]: alright imma add a null check

**Comment by MoonTM-GIT** [comment]
You didn't add that null-check

**Review by MoonTM-GIT — APPROVED** [review]

File: src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java (hunk 3 above)
Comment (MoonTM-GIT) [reply src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java:40]: Yeah, you're right

**Comment by danthe1st** [comment]
> You didn't add that null-check

They have an action in case the request fails but I think that invoking `retrieveMessageById` with a `0` id throws an `IllegalArgumentException` when synchronously.

**Comment by sahilasopa** [comment]
> > You didn't add that null-check
> 
> They have an action in case the request fails but I think that invoking `retrieveMessageById` with a `0` id throws an `IllegalArgumentException` when synchronously.

@danthe1st I tried multiple things to test this, including using this command in empty channels I was not able to reproduce the same errer, can you please tell me when exactly is it thrown?

File: src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java (hunk 3 above)
Comment (sahilasopa) [reply src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java:40]: it is handled actually
`e -> Responses.error(event.getHook(), "Could not retrieve message.").queue())`

**Comment by MoonTM-GIT** [comment]
> > You didn't add that null-check
> 
> They have an action in case the request fails but I think that invoking `retrieveMessageById` with a `0` id throws an `IllegalArgumentException` when synchronously.

Yup, I just looked at the changes of that one commit

File: src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java [hunk 5]
```diff
@@ -19,25 +19,37 @@
  * Command that allows members to format messages.
  */
 public class FormatCodeCommand implements ISlashCommand, IMessageContextCommand {
+	long id;
```
Comment (DynxstyGIT) [inline src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java:22]: Why is `id` a class variable

**Review by DynxstyGIT — CHANGES_REQUESTED** [review]

File: src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java (hunk 5 above)
Comment (sahilasopa) [reply src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java:22]: i will make this private, it is a class variable because its being used in lambda expressions and the require variables to be final or atomic, to keep things simple it was better to make it a class variable

Comment (danthe1st) [reply src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java]: Just create the `id` variable only in the blpcks you need it (`queue` and `else`)?

Comment (sahilasopa) [reply src/main/java/net/javadiscord/javabot/systems/commands/FormatCodeCommand.java]: this wont work as variables are used both in and outside lambda functions (As Far As I Know)

**Review by DynxstyGIT — APPROVED** [review]
