### PR TITLE
Interaction Listener Cleanup & Autocomplete Integration

### LINKED ISSUE #221: Broken Naming Conventions
1. **Describe the bug**
Interfaces are named using c# style.

3. **Expected behavior**
Remove all the I's from the interface class names and use the type.

4. **Additional context**
Just to make sure i wasn't going braindead and name it the descriptive noun.

https://stackoverflow.com/questions/2814805/java-interfaces-implementation-naming-convention

https://stackoverflow.com/questions/2814805/java-interfaces-implementation-naming-convention

### PR DESCRIPTION
**Pull request by DynxstyGIT**
This is a follow-up PR for #244 which attempts to clean up the `InteractionListener` class and adds several uses for the Autocomplete Feature.

## Commands that could work with Autocomplete

- [x] [/jam-admin remove-theme (`name` field)](https://github.com/Java-Discord/JavaBot/pull/245#issuecomment-1085208564)
- [x] [/jam-admin remove-submissions (`id` field)](https://github.com/Java-Discord/JavaBot/pull/245#issuecomment-1085208564)
- [x] [/qotw questions-queue remove (`id` field)](https://github.com/Java-Discord/JavaBot/pull/245#issuecomment-1085222964)
- [x] [/customcommand edit (`name` field)](https://github.com/Java-Discord/JavaBot/pull/245#issuecomment-1085182494)
- [x] [/customcommand delete (`name` field)](https://github.com/Java-Discord/JavaBot/pull/245#issuecomment-1085182494)
- [x] [/db-admin migrate (`name` field)](https://github.com/Java-Discord/JavaBot/pull/245#issuecomment-1085158309)
- [x] ~~/warn discard-by-id (`id` field)~~

## Other
- [x] Add `IAutocomplete` Interface
- [x] Remove `I` prefix from Interface Names (Closes #221)

### CODE REVIEW

**Comment by DynxstyGIT** [comment]
image

**Comment by DynxstyGIT** [comment]
image

**Comment by DynxstyGIT** [comment]
image
image

**Comment by DynxstyGIT** [comment]
image

File: src/main/java/net/javadiscord/javabot/command/interfaces/Autocomplete.java [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+ * Interface that handles Discord's Autocomplete functionality.
+ * <p>
+ * To enable this handler for a particular slash command option, navigate to that
+ * option's entry in the corresponding YAML-file, and add the following property:
+ * <pre><code>
+ * autocomplete: true
+ *     </code></pre>
+ * </p>
+ */
+public interface Autocomplete {
```
Comment (danthe1st) [inline src/main/java/net/javadiscord/javabot/command/interfaces/Autocomplete.java:16]: I would actually rename this to something that implies that something can be used for auto-completion instead of something that **is an** `Autocomplete`. An example would be `Autocompletable`

Comment (DynxstyGIT) [reply src/main/java/net/javadiscord/javabot/command/interfaces/Autocomplete.java:16]: Sure
